name: Github Pages

on:
  push:
    branches:
      - production
      
# Ensure multiple deploys don't overlap, and cause an outdated gh pages
concurrency: 
  group: main_group
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: Build
        run: cd site && hugo --minify
        
      - name: Copy CNAME
        run: cp CNAME ./site/public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public
